[Bug] User Rights for `/data/plugins`
bitnami/bitnami-docker-grafana pull request #12
Opened 2020-12-22 13:40 UTC by Cellebyte

Added the plugins under the uid `1001` instead of root. This should help with the operator issue.

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

2020-12-23 09:22 UTC, rafariossaa reviewed
What about instead of changing the owner doing `chmod a+rwX` instead what is in the line 48 ?

2020-12-23 11:31 UTC, Cellebyte commented
@rafariossaa should also do the trick

2020-12-28 17:01 UTC, Cellebyte commented
@rafariossaa what should be done to resolve this?
It is **blocking** the linked Pull Request bitnami/charts#3287 for the introduction of the grafana-operator helm chart.

2020-12-30 16:48 UTC, rafariossaa commented
Hi, 
  The user 1001 is configurable [here  ](https://github.com/bitnami/bitnami-docker-grafana/blob/1682b91c4bbc21487d68ee8e6500cbea6301f7ec/7/debian-10/Dockerfile#L31) I'd would prefer other kind of solution, instead of harcoding the user id in `graphana-plugins.sh`.

2021-01-04 06:58 UTC, Cellebyte commented
@rafariossaa updated the suggestion.

2021-01-04 13:43 UTC, marcosbc requested changes
Thanks for contributing! Like I mentioned in my comment I don't fully understand the context of this change, it would be really helpful if you could describe what is the current problem and how this PR solves it.

2021-01-04 13:43 UTC, marcosbc commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
Sorry, but I don't fully understand this change. As a non-system user (i.e. no entry in `/etc/passwd`), 1001 should be able to create files in `/opt/bitnami/grafana/data/plugins` without any issues:

```console
$ touch /opt/bitnami/grafana/data/plugins/foo
$ ls -la /opt/bitnami/grafana/data/plugins/
total 12
drwxrwxr-x 1 root root 4096 Jan  4 13:38 .
drwxrwxr-x 1 root root 4096 Jan  4 01:17 ..
-rw-r--r-- 1 1001 root    0 Jan  4 13:38 foo
```

As you can see, the permissions are set to 775 for the folder. Files inside have 644 permissions but belong to 1001 (and this change would not fix that because it is not changing permissions recursively).

So I'm probably missing context here, could you describe further which issues you're finding with the operator?

2021-01-04 14:10 UTC, Cellebyte commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
the issue is not that. We need to be able to delete it to put a symlink in place. Its only bricking pluginInit with the operator chart. I don't know who on your side added the necessary changes to the plugin script. Either fux it like this or fix the script ^^

2021-01-04 14:13 UTC, Cellebyte commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
I can check if we can also solve it in the other script.

2021-01-04 14:57 UTC, marcosbc commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
@Cellebyte Could you clarify what you're referring to?

> We need to be able to delete it to put a symlink in place

Where can we find that logic? Just want to get more context/info to understand whether this change makes sense, or not.

2021-01-04 15:07 UTC, Cellebyte commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
https://github.com/bitnami/bitnami-docker-grafana/blob/master/7/debian-10/rootfs/run.sh

2021-01-04 15:09 UTC, Cellebyte commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
Its the grafana-operator-compatibility part the first function.
It removes all existing folders and creates symlinks for them.
The only folder with issues is the plugins folder.

2021-01-04 15:30 UTC, marcosbc commented on 7/debian-10/rootfs/grafana-plugins.sh
> +chmod a+rwX /opt/bitnami/grafana/data/plugins
Oh, I see, since the `plugins` folder is inside the `data` folder, then the `rm -rf` command fails. In that case, the change LGTM, thanks!

2021-01-04 15:30 UTC, marcosbc approved these changes

2021-01-04 17:33 UTC, andresbono commented
If I'm not wrong, this PR is not going to resolve the issue. The operator launches a grafana container with `uid=1001 gid=1001 groups=1001`. When `grafana_operator_compatibility` function is called, it doesn't have permissions to recursively delete `/opt/bitnami/grafana/data`. If we isolate the executed command, we get the same error:

```
$ docker run --rm --user 1001:1001 --entrypoint rm bitnami/grafana:7.3.4-debian-10-r1 -rf /opt/bitnami/grafana/data
rm: cannot remove '/opt/bitnami/grafana/data/plugins': Permission denied
```

Even though the error message is about `data/plugins`, permissions to delete a directory need to be granted in the parent directory, so I'd say that the proposed solution is not going to work.

Some alternatives:

- Use different securityContext settings so that `1001` is included in the `root` group:

```
helm install --namespace grafana gob . --set grafana.containerSecurityContext.runAsGroup=0
```

- Give write permissions to all users in `/opt/bitnami/grafana/data`. In the Dockerfile: https://github.com/bitnami/bitnami-docker-grafana/blob/823dde80597efedd5179049615c2de85b037532c/7/debian-10/Dockerfile#L19

```diff
-RUN mkdir -p /opt/bitnami/grafana/data/ /opt/bitnami/grafana/logs/ && chmod g+rwX /opt/bitnami/grafana/data/ /opt/bitnami/grafana/logs/
+RUN mkdir -p /opt/bitnami/grafana/data/ /opt/bitnami/grafana/logs/ && chmod a+rwX /opt/bitnami/grafana/data/ /opt/bitnami/grafana/logs/
```

2021-01-05 09:07 UTC, andresbono commented
I just added a third alternative to https://github.com/bitnami/bitnami-docker-grafana/pull/12#issuecomment-754110519, just to make sure you receive a notification.

2021-01-05 11:56 UTC, Cellebyte commented
@andresbono 
```console
cellebyte@t470p:~$  sudo docker run -it -v /tmp/plugins:/opt/plugins -v /tmp/data:/var/lib/grafana -v /tmp/grafana.ini:/etc/grafana/grafana.ini  --rm bitnami/grafana:latest    
Ensuring '/opt/bitnami/grafana/conf/grafana.ini' points to '/etc/grafana/grafana.ini'
Ensuring '/opt/bitnami/grafana/data' points to '/var/lib/grafana'
Detected '/opt/plugins' dir. The container will run as grafana-operator plugins ini
```

2021-01-05 14:00 UTC, Cellebyte commented
@andresbono @marcosbc I changed now the build manifest to do `chown user:root` as suggested by @andresbono.
I tested it today with a local kind cluster.

The only issues I saw had to do with the static file provisioning.
```console
cellebyte@t470p:~$ kubectl logs -f grafana-deployment-d9f5fc5bf-srlb9 -c grafana
Ensuring '/opt/bitnami/grafana/conf/grafana.ini' points to '/etc/grafana/grafana.ini'
Ensuring '/opt/bitnami/grafana/data' points to '/var/lib/grafana'
Ensuring '/opt/bitnami/grafana/logs' points to '/var/log/grafana'
Ensuring '/opt/bitnami/grafana/conf/provisioning' points to '/etc/grafana/provisioning'
t=2021-01-05T12:41:50+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
t=2021-01-05T12:41:50+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
t=2021-01-05T12:41:50+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards error="open /etc/grafana/provisioning/dashboards: no such file or directory"
```
I think this could be left as it is.
Because the operator uses the API of the grafana instance to configure the dashboards.
Not the provisioning endpoints.

2021-01-05 14:16 UTC, Cellebyte commented
@marcosbc please review again.

2021-01-05 15:52 UTC, andresbono commented
Thanks for implementing the latest changes, @Cellebyte. While the solution of using an argument looks very interesting, the addition of a new build argument is not going to 100% match our current documentation and recommendations.

We are going to keep things simple by just hardcoding the username and group. It's something that we are already doing in some cases: https://github.com/bitnami/bitnami-docker-kubewatch/blob/26038b17cc9e01566a19f7041973b977e5797c1d/0/debian-10/Dockerfile#L21

if you don't mind, we will update this PR and we will merge both PRs.

2021-01-06 08:37 UTC, Cellebyte commented
@andresbono its fine for me updating it with the hardcoded version.
Should I do it or do you guys do that?

2021-01-07 08:52 UTC, andresbono commented
> @andresbono its fine for me updating it with the hardcoded version.
> Should I do it or do you guys do that?

We will do that, @Cellebyte. Thanks! We will be doing some testing on our side as well.

2021-01-07 09:08 UTC, Cellebyte commented
@andresbono thanks :)

2021-01-07 17:00 UTC, andresbono approved these changes
LGTM

2021-01-07 17:02 UTC, merged

2021-01-07 18:23 UTC, andresbono commented
bitnami/grafana `7.3.6-debian-10-r20` https://github.com/bitnami/bitnami-docker-grafana/commit/4e24946e05769f872fd1ecab3995aee0c7f11c2c was released including this change.