Added an error code to catch the exception for grafana-operator when …
bitnami/bitnami-docker-grafana pull request #18
Opened 2021-12-01 15:44 UTC by Cellebyte

…it is used as an grafana Plugin Init image

**Description of the change**

**Benefits**

This image now also works again as a plugin init image for grafana-operator.

**Possible drawbacks**

**Applicable issues**
#17 

**Additional information**

2021-12-01 20:01 UTC, Cellebyte commented
@miguelaeh could review this?

2021-12-02 09:52 UTC, miguelaeh commented
Hi @Cellebyte ,
thank you very much for the PR.
I have not understood yet the root of the issue. The `chmod` command seems like a patch more than fixing the actual cause, isn't it?

2021-12-02 10:06 UTC, Cellebyte commented
@miguelaeh the chmod is patching the issue with the filesystem rights.
the `255` error code is there for the immediate exit of the container when it is used by the grafana-operator as a plugin-init.

2021-12-03 10:20 UTC, miguelaeh commented on 8/debian-10/Dockerfile
> +RUN chown 1001:grafana /opt/bitnami/grafana/data
This shouldn't be needed since the postunpack.sh is giving the proper permissions to the group. In the cases when deploying into K8s and the cluster requires special changes an init container can be used instead. Like in our Grafana Helm Chart, where we provide the volumePermission init containers for special cases.

2021-12-03 13:55 UTC, Cellebyte commented on 8/debian-10/Dockerfile
> +RUN chown 1001:grafana /opt/bitnami/grafana/data
@miguelaeh `volumePermission` needs root account which is not the way to go.
it is not possible to start the grafana image.

2021-12-09 07:46 UTC, juan131 requested changes

2021-12-09 07:46 UTC, juan131 commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
Both the **entrypoint.sh** and the **setup.sh** scripts fail a soon as there's an error since they enable the `errexit` shell builtin, see:
```bash
set -o errexit
```
I don't really understand why you need this...

2021-12-09 07:46 UTC, juan131 commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
Please revert these changes... When a container defines an entrypoint, the provided "CMD" usually provides the arguments for the executable defined in the entrypoint.
You can always overwrite the default entrypoint and command in the container in case you want to use a different executable.

2021-12-09 07:46 UTC, juan131 commented on 8/debian-10/Dockerfile
> +RUN chown 1001:grafana /opt/bitnami/grafana/data
I agree with @miguelaeh . This isn't compatible with using arbitrary UID(s) to run the Grafana container.

I think the problem could be related with the line below:

- https://github.com/bitnami/bitnami-docker-grafana/blob/master/8/debian-10/rootfs/opt/bitnami/scripts/grafana/postunpack.sh#L23

We added the `--system` so the `ensure_user_exists` function created a "grafana" system user with UID 999. **This system user is only used when the container is executed as "root" and it's ignored otherwise**.
After that, the permissions are set to `775/664` so both the "grafana" system user and the users belonging to the "root" group have write permissions (this is done to make the container compatible with arbitrary UIDs):

- https://github.com/bitnami/bitnami-docker-grafana/blob/master/8/debian-10/rootfs/opt/bitnami/scripts/grafana/postunpack.sh#L29

When you run the container, by default you're using `user: 1001, group: root` so it should work (since the "root" group has write permissions).

I guess the Grafana Operator is making some assumption and trying to execute certain command as "grafana" user even when the container is executed as a non-root user (e.g. `1001`). Does it make sense?

2021-12-09 13:10 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
Because this functionality was already in the last 7 image and if you read my initial comment on the issue you see the difference in behavior. I am not a shell expert so if there is another solution just use that one I just want to fix all bugs and show the solutions I made as a PR to have a discussion foundation.

2021-12-09 13:12 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
@juan131 the issue is that the containers entrypoint is not starting grafana. But runs the entrypoint script. Do if you provide args it overwrites the run.sh script for grafana.

2021-12-09 13:14 UTC, Cellebyte commented on 8/debian-10/Dockerfile
> +RUN chown 1001:grafana /opt/bitnami/grafana/data
@juan131 I provided an example for the created grafana instance in the pull request for the grafana-operator chart.

2021-12-13 11:03 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
Hi @Cellebyte ,
> So if you provide args it overwrites the run.sh script for grafana and bricks the container.

This is expected, our containers use entrypoint.sh as entrypoint and run.sh as CMD. Grafana is run into the run.sh so, the arguments if you override the CMD must include the full `grafana-server` command

2021-12-13 11:05 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
In any case, isn't that the same as
```
/opt/bitnami/scripts/grafana/setup.sh
GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? 
```
?

2021-12-13 12:34 UTC, miguelaeh commented on 8/debian-10/Dockerfile
> +RUN chown 1001:grafana /opt/bitnami/grafana/data
@juan131 @Cellebyte I added more info about this [here](https://github.com/bitnami/bitnami-docker-grafana/issues/17#issuecomment-992434059)

2021-12-14 10:47 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
I don't know :D If you do me a favor and create a small fix i can apply to validate it.

2021-12-14 10:48 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
@miguelaeh I think so the issue is that the default grafana-container has the grafana-server start as an entrypoint. instead of an entrypoint which needs an executable.

2021-12-14 11:19 UTC, Cellebyte commented
If fixed now Issue number one.

1. :heavy_check_mark: uid  1001 for static rootless and also `<random>999>:0` is supported for openshift.
2. :warning: still discussion needed
3: :warning: still discussion needed

2021-12-14 11:41 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
@miguelaeh This part evaluates to true == 0 as a `$?` which lets bash think it run successfully.
I added now also some kind of exception handling.

2021-12-14 11:47 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    /opt/bitnami/scripts/grafana/setup.sh && GRAFANA_OPERATOR_IMMEDIATE_EXIT=$? || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
@miguelaeh The error code must be `0` so that kubernetes knows the init container run correctly.

2021-12-14 11:55 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
So I invented this implementation which adds the executable if only args are supplied.

2021-12-15 10:25 UTC, miguelaeh requested changes

2021-12-15 10:25 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
I still think this is not needed. Take into account that the grafana operator is overriding both, the `command` and the `args`, which will override the docker `entrypoint` and the `cmd` respectively. https://github.com/bitnami/charts/blob/4bca8a5de4d8d22ce8c6f9cf0c634540ac396dfc/bitnami/grafana-operator/templates/deployment.yaml#L59

2021-12-15 10:25 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/libgrafana.sh
> +        return 255
Why not just changing this to `exit 0` and remove the rest of the logic about the `GRAFANA_OPERATOR_IMMEDIATE_EXIT` ?

2021-12-16 02:19 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/libgrafana.sh
> +        return 255
@miguelaeh because it would not exit the container.

2021-12-16 10:16 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/libgrafana.sh
> +        return 255
With `exit 0` it will exit the process and thus exit the container. After all, in the logic above, you are doing an `exit 0` when the return code returned from this function is `255`.

The only difference I can see between using `exit 0` here, or the implemented changes is that, with the implemented changes the `/post-init.sh` will be executed before exit, while using exit directly it won't. Is that the desired behabiour? I mean, which is the relation between the init scripts and the plugins installation? If there is no relation I guess we can just change `return 255` by `exit 0`

2021-12-16 10:16 UTC, miguelaeh commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
Sorry I misunderstood the previous comments, now I got it

2021-12-16 11:53 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/libgrafana.sh
> +        return 255
If we do an `exit 0` where you suggest it grafana will still start and the unit will never succeed. Because it will not exit.

2021-12-17 09:41 UTC, marcosbc requested changes
Thanks a lot for the contributions! Please check my comments whenever you have a chance.

2021-12-17 09:41 UTC, marcosbc commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
This is a bit hard to read, I would suggest something like this instead: 

```suggestion
    /opt/bitnami/scripts/grafana/setup.sh || GRAFANA_OPERATOR_IMMEDIATE_EXIT=$?
    if [[ "${GRAFANA_OPERATOR_IMMEDIATE_EXIT:-0}" -ne 0 ]]; then
        exit $GRAFANA_OPERATOR_IMMEDIATE_EXIT
    fi
```

2021-12-17 09:41 UTC, marcosbc commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    if [ $GRAFANA_OPERATOR_IMMEDIATE_EXIT -eq 255 ]; then
For this, I don't understand. Why is this logic here if we already check it above? Unless Grafana Operator makes explicit use of `post-init.sh`, I don't see why it would be required.

Also:

```suggestion
    if [[ "${GRAFANA_OPERATOR_IMMEDIATE_EXIT:-0}" -eq 255 ]; then
```

2021-12-17 09:41 UTC, marcosbc commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +fi
Formatting suggestion to be consistent with the codebase:

```suggestion
if is_exec "$1"; then
    exec "$@"
else
    exec "/opt/bitnami/scripts/grafana/run.sh" "$@"
fi
```

It could be simplified even more:

```suggestion
is_exec "$1" && exec "$@"
exec "/opt/bitnami/scripts/grafana/run.sh" "$@"
```

2021-12-17 10:52 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
I don‘t know if that is the same behavior as before.
Does this ensure that the exit code is `0` when `255` was raised?

2021-12-17 10:56 UTC, marcosbc commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
With the proposed improvement, it would exit whenever `GRAFANA_OPERATOR_IMMEDIATE_EXIT` has a value different than `0`. And if `setup.sh` does not fail, `GRAFANA_OPERATOR_IMMEDIATE_EXIT` will default to `0` so it will not exit.

2021-12-17 10:58 UTC, marcosbc commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
Oh, I see now. So yes, you are right, this would need to be changed like this:

```
if [[ "${GRAFANA_OPERATOR_IMMEDIATE_EXIT:-0}" -eq 255 ]]; then
    exit 0
elif [[ "${GRAFANA_OPERATOR_IMMEDIATE_EXIT:-0}" -ne 0 ]]; then
    exit "$GRAFANA_OPERATOR_IMMEDIATE_EXIT"
fi
```

2021-12-17 10:59 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
Jep I am also fine removing the additional check after the init scripts in favor of this solution :)

2021-12-17 14:00 UTC, Cellebyte commented on 8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh
> +    fi
@marcosbc I applied all you changes now.
Thanks for the help :)

2021-12-20 11:42 UTC, javsalgar commented
Just a note to let you know that @marcosbc is on PTO. As soon as he comes back he will provide more feedback.

2021-12-27 11:40 UTC, marcosbc approved these changes
LGTM! Thanks for this contribution! We will merge it shortly.

2021-12-27 13:40 UTC, merged

2022-01-07 16:05 UTC, js-timbirkett commented
I still see problems on startup relating to permissions in the init container:

```
grafana-plugins-init grafana 16:01:02.85 
grafana-plugins-init grafana 16:01:02.85 Welcome to the Bitnami grafana container
grafana-plugins-init grafana 16:01:02.85 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-grafana
grafana-plugins-init grafana 16:01:02.85 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-grafana/issues
grafana-plugins-init grafana 16:01:02.85 
grafana-plugins-init grafana 16:01:02.86 INFO  ==> Detected mounted plugins directory at '/opt/plugins'. The container will exit after installing plugins as grafana-operator.
grafana-plugins-init grafana 16:01:02.86 WARN  ==> There are no plugins to install
grafana grafana 16:01:25.65 
grafana grafana 16:01:25.66 Welcome to the Bitnami grafana container
grafana grafana 16:01:25.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-grafana
grafana grafana 16:01:25.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-grafana/issues
grafana grafana 16:01:25.66 
grafana grafana 16:01:25.67 INFO  ==> Ensuring /etc/grafana/grafana.ini points to /opt/bitnami/grafana/conf/grafana.ini
grafana rm: cannot remove '/opt/bitnami/grafana/conf/grafana.ini': Permission denied
Stream closed EOF for monitoring/grafana-deployment-f5f9d479c-2vd5m (grafana)
Stream closed EOF for monitoring/grafana-deployment-f5f9d479c-2vd5m (grafana-plugins-init)

```

2022-01-10 13:07 UTC, marcosbc commented
@js-timbirkett That looks like a warning, is it causing the container to fail?